### GET ALL PRODUCTS
GET http://localhost:8080/products

### CREATE ONE PRODUCT
POST http://localhost:8080/products
Content-Type: application/json

{
    "name": "Double shot",
    "description": "I need a double shot of whatever my kids are on",
    "category": "Clothing",
    "type": "Sweatshirt",
    "size": "Large",
    "color": "Red",
    "price": 13.50
}

// PRODUCTION

### GET ALL PRODUCTS
GET https://cse341-lesson5.herokuapp.com/products

### CREATE ONE PRODUCT
POST https://cse341-lesson5.herokuapp.com/products
Content-Type: application/json

{
    "name": "Squad Mama",
    "description": "My kids call me Squad Mama",
    "category": "Clothing",
    "type": "Shirt",
    "size": "Medium",
    "color": "Black",
    "price": 10.50
}